/**
 * Velmora — Roofing Contractor Demo System
 * ------------------------------------------------------------------
 * Centralized type definitions for the complete per-client data
 * document (src/data/company.config.json).
 *
 * Every UI component consumes this configuration through props.
 * No company-specific information is embedded in components, so a
 * new client's demo site is generated by replacing the JSON only.
 */

/** Core identity block for a roofing company. */
export interface CompanyInfo {
  name: string
  /** Display + tel: source phone number. */
  phone: string
  email: string
  address: string
  city: string
  state: string
  /** Pre-formatted "City, ST" string. */
  city_state: string
  logo_url?: string
  years_in_business?: number
  /** Whether the company advertises 24/7 emergency service. */
  emergency_service?: boolean
  marquee_phrase?: string
}

/** Hero section content. */
export interface HeroContent {
  headline: string
  subheadline: string
  image?: string
  /** Primary CTA label, usually "Get a free quote/inspection". */
  primary_cta: string
  /** Secondary CTA label, usually "Call us now". */
  secondary_cta: string
  eyebrow?: string
  /** Quick-win chips under the CTAs (e.g. "Free Inspections"). */
  perks?: string[]
}

/** Google rating summary. */
export interface RatingSummary {
  google_rating: number
  review_count: number
  /** Optional link to the Google Business profile. */
  review_url?: string
}

/** A service offering card. */
export interface Service {
  id: string
  name: string
  description: string
  /** Lucide icon name mapped by the UI (see lib/iconMap). */
  icon: string
  image?: string
  /** Optional emphasis badge, e.g. "Most Popular". */
  badge?: string
}

/** Individual Google review entry. */
export interface Review {
  id: string
  author: string
  location?: string
  rating: number
  date?: string
  text: string
  service?: string
}

/** Long-form customer testimonial. */
export interface Testimonial {
  id: string
  name: string
  location?: string
  rating: number
  text: string
  project_type?: string
}

/** Portfolio / project showcase entry. */
export interface Project {
  id: string
  title: string
  location?: string
  before_image?: string
  after_image?: string
  image: string
  description?: string
  /** e.g. "Roof Replacement", "Storm Damage Repair". */
  type?: string
  year?: string
  /** Outcome detail, e.g. "Completed in 2 days". */
  result?: string
}

/** Credibility badge (licensing, insurance, warranty, certifications). */
export interface TrustBadge {
  id: string
  label: string
  detail?: string
  icon: string
}

/** Credibility block: raw guarantee flags + badge list for rendering. */
export interface TrustBlock {
  licensed: boolean
  insured: boolean
  warranty: boolean
  warranty_text: string
  license_number?: string
  badges: TrustBadge[]
}

/** Emergency roof response banner strip. */
export interface EmergencyBanner {
  enabled: boolean
  title: string
  description: string
  phone: string
}

/** Repeatable contact information for footer / contact sections. */
export interface ContactInfo {
  email: string
  phone: string
  address: string
  hours: string
}

/** External profiles, keyed by platform. */
export interface SocialChannels {
  facebook?: string
  instagram?: string
  google?: string
}

/** Standalone metric, e.g. "3,500+ Roofs Completed". */
export interface Stat {
  id: string
  value: string
  label: string
}

/** Final conversion block near the end of a page. */
export interface FinalCTA {
  heading: string
  description: string
  button_label: string
}

/** Selection key for the three built-in site templates. */
export type TemplateId = 'template-1' | 'template-2' | 'template-3'

/** Top-level business data document for every Velmora customer. */
export interface CompanyConfig {
  /** Which template renders this site. Falls back to "template-1". */
  template?: TemplateId
  company: CompanyInfo
  hero: HeroContent
  ratings: RatingSummary
  services: Service[]
  reviews: Review[]
  testimonials: Testimonial[]
  projects: Project[]
  trust: TrustBlock
  emergency: EmergencyBanner
  contact: ContactInfo
  social: SocialChannels
  stats: Stat[]
  final_cta: FinalCTA
}