/**
 * Velmora — Roofing Contractor Demo System
 * ------------------------------------------------------------------
 * Centralized type definitions for the complete per-client data
 * document (src/data/company.config.json).
 *
 * Every UI component consumes this configuration through props.
 * No company-specific information is embedded in components, so a
 * new client's demo site is generated by replacing the JSON only.
 */

/** Core identity block for a roofing company. */
export interface CompanyInfo {
  name: string
  /** Authoritative display + tel: source phone number. */
  phone: string
  email: string
  address: string
  city: string
  state: string
  /** Pre-formatted "City, ST" string. */
  city_state: string
  logo_url?: string
  years_in_business?: number
  /**
   * Claimed estimate/response turnaround, e.g. "within 24 hours".
   * Render only when present — never invent a response time.
   */
  response_time?: string
  /** Kept for backwards compatibility; prefer emergency.enabled. */
  emergency_service?: boolean
  marquee_phrase?: string
}

/** Hero section content. */
export interface HeroContent {
  headline: string
  subheadline: string
  image?: string
  /** Primary CTA label, usually "Get a free quote/inspection". */
  primary_cta: string
  /** Secondary CTA label, usually "Call us now". */
  secondary_cta: string
  eyebrow?: string
  /** Quick-win chips under the CTAs (e.g. "Free Inspections"). */
  perks?: string[]
}

/** Google rating summary. */
export interface RatingSummary {
  google_rating: number
  review_count: number
  /** Optional link to the Google Business profile. */
  review_url?: string
}

/** A service offering card. */
export interface Service {
  id: string
  name: string
  description: string
  /** Lucide icon name mapped by the UI (see lib/iconMap). */
  icon: string
  image?: string
  /** Optional emphasis badge, e.g. "Most Popular". */
  badge?: string
}

/** Individual Google review entry. */
export interface Review {
  id: string
  author: string
  location?: string
  rating: number
  date?: string
  text: string
  service?: string
}

/** Long-form customer testimonial. */
export interface Testimonial {
  id: string
  name: string
  location?: string
  rating: number
  text: string
  project_type?: string
}

/** Portfolio / project showcase entry. */
export interface Project {
  id: string
  title: string
  location?: string
  before_image?: string
  after_image?: string
  image: string
  description?: string
  /** e.g. "Roof Replacement", "Storm Damage Repair". */
  type?: string
  year?: string
  /** Outcome detail, e.g. "Completed in 2 days". */
  result?: string
}

/** Credibility badge (licensing, insurance, warranty, certifications). */
export interface TrustBadge {
  id: string
  label: string
  detail?: string
  icon: string
}

/** Credibility block: raw guarantee flags + badge list for rendering. */
export interface TrustBlock {
  licensed: boolean
  insured: boolean
  warranty: boolean
  warranty_text: string
  license_number?: string
  /** Whether to advertise free estimates (e.g. "Free, itemized estimates"). */
  free_estimates?: boolean
  badges: TrustBadge[]
}

/** Emergency roof response banner strip. */
export interface EmergencyBanner {
  enabled: boolean
  title: string
  description: string
  /** Optional dedicated emergency line. Falls back to company.phone. */
  phone?: string
}

/** Repeatable contact information for footer / contact sections. */
export interface ContactInfo {
  /**
   * Optional; falls back to company.email so company.* stays authoritative.
   */
  email?: string
  /**
   * Optional; falls back to company.phone so company.* stays authoritative.
   */
  phone?: string
  /** Optional; falls back to company.address. */
  address?: string
  hours: string
}

/** Optional financing offer (0% financing, etc.). Renders only when enabled. */
export interface FinancingInfo {
  enabled: boolean
  label?: string
}

/** Conversion CTA labels reused across site chrome and CTAs. */
export interface CtaLabels {
  /** Header primary button, e.g. "Get Free Estimate". */
  header?: string
  /** Mobile sticky bar call label. */
  mobile_call?: string
  /** Mobile sticky bar quote label. */
  mobile_quote?: string
  /** "Book a free inspection" style hero CTA. */
  book_inspection?: string
  /** "See our work" style hero CTA. */
  see_work?: string
  /** Guarantee section call button. */
  guarantee_call?: string
  /** Guarantee section quote button. */
  guarantee_book?: string
}

/** Quote-form copy (title, subtitle, submit + trust line). */
export interface QuoteFormCopy {
  title?: string
  subtitle?: string
  button_label?: string
  trust_note?: string
}

/** External profiles, keyed by platform. */
export interface SocialChannels {
  facebook?: string
  instagram?: string
  google?: string
}

/** Standalone metric, e.g. "3,500+ Roofs Completed". */
export interface Stat {
  id: string
  value: string
  label: string
}

/** Final conversion block near the end of a page. */
export interface FinalCTA {
  heading: string
  description: string
  button_label: string
}

/** Selection key for the three built-in site templates. */
export type TemplateId = 'template-1' | 'template-2' | 'template-3'

/** Top-level business data document for every Velmora customer. */
export interface CompanyConfig {
  /** Which template renders this site. Falls back to "template-1". */
  template?: TemplateId
  company: CompanyInfo
  hero: HeroContent
  ratings: RatingSummary
  services: Service[]
  reviews: Review[]
  testimonials: Testimonial[]
  projects: Project[]
  trust: TrustBlock
  emergency: EmergencyBanner
  contact: ContactInfo
  social: SocialChannels
  stats: Stat[]
  final_cta: FinalCTA
  /** Optional financing offer; renders only when enabled. */
  financing?: FinancingInfo
  /** Reused CTA labels across site chrome. */
  cta?: CtaLabels
  /** Quote-form title, subtitle, button, trust-note overrides. */
  quote_form?: QuoteFormCopy
}